# -*- coding: utf-8 -*-
"""Notebook 2 - Complemento a 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1651n86ZQ3RASkAz6sgNR8D66w5L4Gax8

<h1>COMPLEMENTO A DUE</h1><h2>(Rappresentare i numeri interi con sequenze di bit)</h2>

Per implementare il complemento a due in Python abbiamo bisogno delle due implementazioni dell'algoritmo di Horner e del suo inverso già discusse nel Notebook 1. Il codice viene riportato qui con qualche adattamento legato al fatto che lavoriamo solo in base 2. Nel caso dell'algoritmo inverso, l'algoritmo permette di specificare la lunghezza della sequenza in output.
"""

def horner2(input):

    output = 0

    for k in range(0,len(input)):

        output = output * 2 + int(input[k])

    return output

horner2('100010')

"""Il codice qui sotto assume di default che la sequenza debba essere lunga 16 bit, ma se un secondo input viene specificato produce una sequenza più breve."""

def invhorner2(input, sequencelength=16):

    output = ''

    while(input) > 0 or len(output)< sequencelength:

        bit = input % 2

        input = int((input - bit) / 2)

        output = str(bit) + output

    return output

print(invhorner2(34))
print(invhorner2(34,8))

"""<h2>Complemento a 2<h2>
<h3>Conversione da bit a numero</h3>
L'algoritmo prima converte la sequenza di bit in un numero naturale applicando l'algoritmo di Horner. Se il primo bit è zero, questo è già il risultato che viene restituito in output, laddove se il primo bit è invece uno, si calcola effettivamente il complemento, ovvero $-(2^n-x)$ dove $x$ è il numero naturale ottenuto con Horner ed $n$ il numero di bit della sequenza con cui stiamo lavorando.
"""

def bits2int(input):

  x = horner2(input)

  if input[0] == '0':

    output = x

  else:

    output = -(2**len(input)-x)

  return output

"""<h3>Conversione da bit a numero</h3>
In questo caso l'algoritmo testa se il numero da convertire in una sequenza di bit è non-negativo. In questo caso la conversione è banalmente prodotta dall'inverso dell'algoritmo di Horner. Se invece il numero in input è negativo, l'algoritmo calcola il valore di complemento $2^n+x$ dove $n$ è il numero di bit con cui stiamo lavorando e $x$ è il numero (negativo) in input e ne fa la conversione in base due. Nota che essendo $x$ negativo, fare $2^n+x$ corrisponde a sottrare a $2^n$ il valore assoluto di $x$.
"""

def int2bits(input,lengthsequence):

  if input >= 0:

    output = invhorner2(input,lengthsequence)

  else:

    output = invhorner2(2**lengthsequence+input,lengthsequence)

  return output

"""Esercizi presenti sulle slides"""

print(bits2int('11110010'))
print(int2bits(-34,8))
print(bits2int('1000111011101000'))
print(bits2int('0010000000101000'))
print(int2bits(-20720,16))
print(int2bits(-32700,16))