# -*- coding: utf-8 -*-
"""Notebook 0 - Operazioni di Base e Somma primi n numeri.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pGNyDG94S0ykXq7CUFh61_k3XVfZrejm
"""

a = 2
b = 3
print(a+b)

for contatore in range(5):
  print("Ciao ",contatore)

for i in range(10):
  if i % 3 == 0:
    print(i,"è un multiplo di 3")
  else:
    print(i,"non è un multiplo di 3")

dizionario = {"Rosso" : 31, "Verde" : 43, "Blue" : 81}
print(dizionario["Rosso"])
print(dizionario)

v = [1,2,3,5,8,13]
print(v[0])
print(v[1:3])
print(v[-1])
for e in v:
  print(e)

def somma_primi_n_numeri(n):
  somma = (n+1)*n/2
  return somma

def somma_primi_n_numeri_slow(n):
  somma = 0
  for contatore in range(n+1):
    somma = somma + contatore
  return somma

print(somma_primi_n_numeri(100))
print(somma_primi_n_numeri_slow(100))