# -*- coding: utf-8 -*-
"""Unità 3 - Horner Frazionario e suo Inverso.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gN1jprFv_OJXEFKTSX6kMZpWS8adec6m

<h1>Algoritmo di Horner per numeri frazionari</h1>
L'algoritmo riceve in input un array [b1,...,bn] le cui cifre rappresentano un numero frazionario della forma 0.[b1,...,bn]. Di default l'algoritmo assume che la base sia 2, ma l'utente può specificare opzionalmente una base diversa che corrisponde al secondo input della funzione.

L'algoritmo rovescia la sequenza perché occorre partire da dx e non da sx (come fa Horner per i numeri interi). Arrivato in fondi bisogna ancora divider per la base e sommare lo zero a sinistra della virgola, cosa fatta dalla riga finale (quella del return)
"""

def horner_fraz(sequenza, base=2):
  # Supporto a conversioni in esadecimale (vedi Lez 1)
  str2int = {'0':0, '1':1, '2':2, '3':3, '4':4, '5':5, '6':6, '7':7, '8':8, '9':9, 'A':10, 'B':11, 'C':12, 'D':13, 'E':14, 'F':15}
  if base>10:
    sequenza = [str2int[_] for _ in sequenza]
  # Algoritmo
  numero = 0
  for bit in sequenza[::-1]:
    numero = numero/base + int(bit)
  return numero/base

"""<h1>Inverso dell'algoritmo di Horner per numeri frazionari</h1>
L'algoritmo riceve in input un numero. Dopodiche svolge iterativamente le seguenti operazioni:

*   Divisione intera per la base, cosa che produce la prossima cifra (bit)
*   Aggiornamento della variabile numero

In questa implementazione l'algoritmo termina quando numero diventa 0 (e quindi la conversione è esatta) oppure dopo un numero massimo di iterazioni (in questo caso 24)

"""

def inv_horner_fraz(numero,base=2):
  # Supporto a conversioni in esadecimale (vedi Lez 1)
  int2str = ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'A', 'B', 'C', 'D', 'E', 'F']
  sequenza = ''
  # Algoritmo
  contatore = 0
  while(numero>0 and contatore<24):
    bit = int((numero*base)//1)
    sequenza = sequenza+str(bit)
    numero = numero*base - bit
    contatore += 1
  return sequenza

print(horner_fraz([0,1,1]))
print(inv_horner_fraz(0.375))
print(horner_fraz([5,3,7,1],8))
print(inv_horner_fraz(0.686,8))
print(inv_horner_fraz(0.52))
print(inv_horner_fraz(horner_fraz(['1','A','0','F'],16),2))
print(inv_horner_fraz(horner_fraz([5,1,7],8)))