# -*- coding: utf-8 -*-
"""Notebook 1 - Algoritmo di Horner ed Inverso.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rjCcQMtkfmHeLEm593Ew3JlXm2dEoQSd

<h1>ALGORITMO DI HORNER E SUO INVERSO</h1><h2>(Numeri Naturali)</h2>

In questo notebook descriviamo i numeri in base diversa da 10 come stringhe (= sequenze di caratteri). Questo è praticamente indispensabile se si lavora con basi $>10$ (es. esadecimale), con alcune cifre che corrispondono a lettere. Per definire la corrispondenza fra cifre e numeri usiamo un <i>dizionario</i> (o hash table) di Python (https://www.python.it/doc/Howtothink/Howtothink-html-it/chap10.htm).
"""

str2int = {'0':0, '1':1, '2':2, '3':3, '4':4, '5':5, '6':6, '7':7, '8':8, '9':9, 'A':10, 'B':11, 'C':12, 'D':13, 'E':14, 'F':15}

"""Vice versa, per trovare la cifra (non-decimale) associata ad un valore numerico usiamo la seguente lista (https://www.python.it/doc/Howtothink/Howtothink-html-it/chap08.htm)."""

int2str = ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'A', 'B', 'C', 'D', 'E', 'F']

"""<h1>Algoritmo di Horner</h1>
<p>Dato un numero in base "b" (con il numero espresso come una stringa) il seguente algoritmo calcola il valore dello stesso numero in base 10.</p>
"""

def horner(number, b):

    output = 0

    for k in range(0,len(number)):

        output = output * b + str2int[number[k]]

    return output

horner('10010',2)

"""<h1>Inverso dell'Algoritmo di Horner</h1>
<p>Dato un numero in base 10 ed una base "b", calcola la rappresentazione dello stesso numero in base "b" (come una stringa).</p>
"""

def invhorner(number, b):

    output = ''

    while(number) > 0:

        digit = number % b

        number = int((number - digit) / b)

        output = int2str[digit] + output

    return output

invhorner(18,2)

"""La combinazione (nested) dei due algoritmi permette di passare da una base di partenza b1 ad una base di arrivo b2."""

def basechange(number, b1, b2):

    return invhorner(horner(number, b1), b2)

basechange('1101',2,3)

"""<h2>Correzione Esercizi delle Slides</h2>"""

print(invhorner(131086,2))

print(horner('1302',4))
print(horner('200102',3))
print(horner('2177',8))
print(horner('AC12',16))
print(horner('1111',3))
print(horner('1111',4))
print('--')
print(invhorner(2143,2))
print(invhorner(13458,16))
print(invhorner(798,8))
print(invhorner(144,2))
print(invhorner(144,3))
print(invhorner(144,4))
print('--')
print(basechange('1032',4,3))
print(basechange('101101',2,5))
print(basechange('2177',8,16))
print('--')
print(basechange('1032',4,2))
print(basechange('101101',2,16))
print(basechange('2177',8,2))
print('--')
print(basechange('10220',3,9))
print(basechange('20016',7,5))
print(basechange('AC16',16,8))
print('--')
print(horner('1111',2))
print(horner('11111',2))
print(horner('111111',2))
print(horner('222',3))
print(horner('2222',3))
print(horner('22222',3))
print(horner('44',5))
print(horner('444',5))
print(horner('4444',5))
print('--')
print(horner('A019',16))
print(horner('010C7142',16))
print(horner('0000100A00073501',16))

invhorner(12,2)
horner('1011011011001111',2)